name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

  doxygen:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.2
        with:
          doxyfile-path: ./Doxyfile
          working-directory: .
